### ISSUE TITLE
not compat with  {.gcsafe.}?

### ISSUE THREAD

**Issue by ITwrx** [PhilippMDoerner/nimword#11]
hi,
I'm trying to use nimword with Guildenstern and my program [won't compile](https://github.com/olliNiinivaara/GuildenStern/issues/19) . It seems to me that it's breaking the `{.gcsafe.}` from Guildenstern.  
thanks

**Comment by PhilippMDoerner** [comment]
A more elaborate minimal example for easier reproduction would be nice :smile:

**Comment by PhilippMDoerner** [comment]
> Sorry about the lack of an example. I'm usually pretty good about that. In fact, at first i thought you were making fun of how verbose my example was, but that was https://github.com/olliNiinivaara/SQLiteral/issues/8. 🙂

Personally I regard these always as a goldmine for figuring out what went wrong, so I agree with your general stance :smile: .
It can of course be so much that suddenly there's heavy work involved in filtering for the relevant stuff, but that tends to be the rare exception.

As for this issue in particular: It's mostly information for the user about what exceptions may arise. It allows you to know at the boundaries of my API what exceptions may await you, you won't have to go digging in the codebase.
For the most part raises actually is irrelevant. It is when somebody else defines `raises: []` (meaning no Exception is allowed to happen) when this becomes useful - because it unifies the place where you can look for what errors may be thrown instead of forcing you to go digging through Codebases.

What would've been nice here would be to avoid `Exception` in my own raises block. The issue here lies in the fact that I don't know what part of my code raises `Exception`.
Even if I were to surround the entire proc-codeblock with a `try-except Exception:` it would not help, as the effects system would still register that an Exception may occur somewhere. Where? No Idea. Basically your error msg would be `Error: isValidPassword("lala", hash) can raise an unlisted exception: Exception`

**Comment by ITwrx** [comment]
Thanks for the explanation! closing.
